version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "/dockerhub/credentials:DOCKERHUB_PASS"
    DOCKERHUB_USERNAME: "/dockerhub/credentials:DOCKERHUB_USERNAME"
phases:
  install:
    commands:
      - echo pre_build step...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS


  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t week4 .
      - docker tag  week4:latest gopalgupta123456789/week4:latest
    post_build:
      commands:
        - echo Build completed on `date`
        - docker push gopalgupta123456789/week4:latest