version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_NO}:secret:dockerhub-Y24wXP:password"
    DOCKERHUB_USERNAME: "arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_NO}:secret:dockerhub-Y24wXP:username"
    GIT_TOKEN: "arn:aws:secretsmanager:${AWS_REGION}:${AWS_ACCOUNT_NO}:secret:dockerhub-Y24wXP:git_token"
    
  exported-variables:
    #- CODEBUILD_BUILD_ID
    - CODEBUILD_BUILD_NUMBER

phases:
  install:
    commands:
      - echo pre_build step...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - echo configuring git credential
      - git clone https://github.com/gopal1gupta/demoargocd
      - ls
      - sed --version 


      


  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t week4 .
      - docker tag  week4:latest ${IMAGE_REPO}/${NAME}:$CODEBUILD_BUILD_NUMBER
      - docker push ${IMAGE_REPO}/${NAME}:$CODEBUILD_BUILD_NUMBER
      - cd demoargocd
      - sed -i "s|gopalgupta12345678.*|${IMAGE_REPO}/${NAME}:$CODEBUILD_BUILD_NUMBER|g" deployment.yaml
      - git config --global user.email "gopalgupta8013@gmail.com"
      - git config --global user.name "gopal1gupta"
      - git remote set-url origin "https://${GIT_TOKEN}@github.com/gopal1gupta/demoargocd"
      - git branch
      - git remote -v
      - git add .
      - git commit -m "updating deployment.yaml"
      - git push origin main

    post_build:
      commands:
        - echo Build completed on `date`
